name: Build Debug
on:
 push:
 workflow_dispatch:
 schedule:
   - cron: '1 2 */86 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew         
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Build app bundle 
        run: ./gradlew app:bundle
      - name: generated APK file
        uses: actions/upload-artifact@v2
        with:
         name: data-livewallpaper-debug
         path: ./app/build/outputs/apk/debug
      - name: generated app bundle
        uses: actions/upload-artifact@v2 
        with:
         name: app bundle
         path: ./app/build/outputs//bundle/debug/app.aab

        
