name: Build Debug
on:
 
 workflow_dispatch:
 schedule:
   - cron: '1 2 */86 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew         
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Build app bundle 
        run: ./gradlew app:bundle
      - name: generated APK file
        uses: actions/upload-artifact@v2
        with:
         name: data-livewallpaper-debug(.apk)
         path: ./app/build/outputs/apk/debug/*.apk
      - name: generated app bundle
        uses: actions/upload-artifact@v2 
        with:
         name: bundletool(.aab)
         path: ./app/build/outputs/bundle/debug
      - name: bundletool build-apks
        run: java -jar ./bundletool.jar build-apks --bundle=./app/build/outputs/bundle/debug/app-debug.aab --output=./MyApp/my_app.apks
      - name: apks
        uses: actions/upload-artifact@v2 
        with:
         name: apks(.apks)
         path: ./MyApp/my_app.apks
      - name: bundletool build-apks nokia5.json
        run: java -jar ./bundletool.jar build-apks --device-spec=./nokia5.json --bundle=./app/build/outputs/bundle/debug/app-debug.aab --output=./MyApp/nokia5_app.apks
      - name: apks nokia5
        uses: actions/upload-artifact@v2 
        with:
         name: nokia5(.apks)
         path: ./MyApp/nokia5_app.apks
      - name: tree
        run: |
         echo install tree
         sudo apt-get install -y tree
         echo ***./app/build/outputs/***
         tree -h ./app/build/outputs/
         echo ***./MyApp/***
         tree -h ./MyApp/
         
      - name: Display  
        uses: actions/download-artifact@v2
      - name: Display structure of downloaded files  
        run: ls -R
         
         
