name: Unit tests

on:
  workflow_dispatch:

  pull_request_target:
    branches:
      - '**' 
  schedule:
    - cron: '1 2 */17 * *'
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Execute tests
      run: |
       cd ./gradle/wrapper
       rm gradle-wrapper.jar
       RELEASE=$(curl -L -s -H 'Accept: application/json' https://services.gradle.org/versions/current | jq .version | sed -e 's/"//g')
       echo -e "\033[31;1m Gradle wrapper: \033[0m"
       echo RELEASE = $RELEASE
       URL=$(curl -s -L -o gradle.zip https://services.gradle.org/distributions/gradle-$(curl -L -s -H 'Accept: application/json' https://services.gradle.org/versions/current | jq .version | sed -e 's/"//g')-src.zip)
       wrapper=$(unzip -j -d . gradle.zip gradle-$(curl -L -s -H 'Accept: application/json' https://services.gradle.org/versions/current | jq .version | sed -e 's/"//g')/gradle/wrapper/gradle-wrapper.jar)
       SHA=$(curl -s --location --output gradle-wrapper.jar.sha256 https://services.gradle.org/distributions/gradle-$(curl -L -s -H 'Accept: application/json' https://services.gradle.org/versions/current | jq .version | sed -e 's/"//g')-wrapper.jar.sha256)
       echo "  gradle-wrapper.jar" >> gradle-wrapper.jar.sha256
       sha256sum --check gradle-wrapper.jar.sha256
       rm gradle.zip
       cd ..
       cd ..
       chmod +x ./gradlew 
       echo --------------------------------------*
       echo -e "\033[31;1m Gradle Version switch to Latest version \033[0m"
       ./gradlew wrapper --gradle-version=$RELEASE
       ./gradlew -v 
       echo -e "\033[31;1m Gradle Test \033[0m"
       ./gradlew test
       
    - name: 🤖dependabot[bot]  Gradle assembleDebug
      if: ${{ github.actor == 'dependabot[bot]' }}
      run: ./gradlew assembleDebug

     
       
  timestamp:
      runs-on: ubuntu-latest
      needs: testing
      steps:
      - uses: actions/checkout@v2
      - name: Timestamp Unit tests
        shell: bash
        run: |
           date >> ./timestamp
           zone=$(TZ='Europe/Bratislava' date -r ./timestamp)
           sed -i "7s/.*/- #####  Unit tests: $zone/" ./README.md
           echo Timestamp : $zone
           git config --global user.email ${{ secrets.EMAIL }}
           git config --global user.name ${{ secrets.NAME }}        
           git add ./README.md
           git commit -m "timestamp" ./README.md
           git push --force         

  
  
