name: Unit tests

on:
  workflow_dispatch:
  pull_request_target:
    branches: '**' 

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Execute tests
      run: |
       echo -e "\033[31;1m Bundletool Version download Latest version\033[0m"
       RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/google/bundletool/releases/latest)
       VERSION=$(echo $RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
       echo VERSION = $VERSION
       echo $VERSION
       URL=$(curl -s -L -o ./bundletool.jar https://github.com/google/bundletool/releases/download/$(echo $RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')/bundletool-all-$(echo $RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/').jar)      
       echo --------------------------------------*
       cd ./gradle/wrapper
       rm gradle-wrapper.jar
       RELEASE=$(curl -L -s -H 'Accept: application/json' https://services.gradle.org/versions/current | jq .version | sed -e 's/"//g')
       echo -e "\033[31;1m Gradle wrapper: \033[0m"
       echo RELEASE = $RELEASE
       echo $RELEASE
       URL=$(curl -s -L -o gradle.zip https://services.gradle.org/distributions/gradle-$RELEASE-src.zip)
       wrapper=$(unzip -j -d . gradle.zip gradle-$RELEASE/gradle/wrapper/gradle-wrapper.jar)
       SHA=$(curl -s --location --output gradle-wrapper.jar.sha256 https://services.gradle.org/distributions/gradle-$(curl -L -s -H 'Accept: application/json' https://services.gradle.org/versions/current | jq .version | sed -e 's/"//g')-wrapper.jar.sha256)
       echo "  gradle-wrapper.jar" >> gradle-wrapper.jar.sha256
       sha256sum --check gradle-wrapper.jar.sha256
       rm gradle.zip
       sed -i 6i"distributionUrl=https\://services.gradle.org/distributions/gradle-$RELEASE-all.zip" gradle-wrapper.properties
       cd ..
       cd ..
       chmod +x ./gradlew 
       echo --------------------------------------*
       echo -e "\033[31;1m Gradle Version switch to Latest version \033[0m"
       ./gradlew wrapper --gradle-version=$RELEASE --quiet
       ./gradlew -v 
       echo -e "\033[31;1m Gradle Test \033[0m"
       ./gradlew test
       
    - name: 🤖dependabot[bot]  Gradle assembleDebug
      if: ${{ github.actor == 'dependabot[bot]' }}
      run: ./gradlew assembleDebug

     
       
  timestamp:
      runs-on: ubuntu-latest
      needs: testing
      steps:
    # - uses: actions/checkout@v2
      - name: Timestamp Unit tests
        shell: bash
        run: |
           git pull --rebase
           timestamp=$(TZ='Europe/Bratislava' date)
           sed -i "7s/.*/- #####  Unit tests: $timestamp/" ./README.md
           echo $timestamp
           git config --global user.email ${{ secrets.EMAIL }}
           git config --global user.name ${{ secrets.NAME }}        
           git add -u 
           git commit -m "$timestamp" ./README.md
           git push        
         
  

     
