name: Unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - '**' 
  pull_request:
    branches:
      - '**' 

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Execute tests
      run: |
       chmod +x ./gradlew  
        echo Gradle Version
       ./gradlew -v 
       ./gradlew test --console=(auto,plain,rich,verbose)
