name: Unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - '**' 
  pull_request:
    branches:
      - '**' 
  schedule:
    - cron: '1 2 */17 * *'
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Execute tests
      run: |
       echo Gradle wrapper
       chmod +x ./gradlew
       ./gradlew -v 
       cd ./gradle/wrapper
       rm gradle-wrapper.jar
       RELEASE=$(curl -L -s -H 'Accept: application/json' https://services.gradle.org/versions/current | jq .version | sed -e 's/"//g')
       echo Gradle Version:
       echo RELEASE = $RELEASE
       URL=$(curl -s -L -o gradle.zip https://services.gradle.org/distributions/gradle-$(curl -L -s -H 'Accept: application/json' https://services.gradle.org/versions/current | jq .version | sed -e 's/"//g')-src.zip)
       wrapper=$(unzip -j -d . gradle.zip gradle-$(curl -L -s -H 'Accept: application/json' https://services.gradle.org/versions/current | jq .version | sed -e 's/"//g')/gradle/wrapper/gradle-wrapper.jar)
       SHA=$(curl -s --location --output gradle-wrapper.jar.sha256 https://services.gradle.org/distributions/gradle-$(curl -L -s -H 'Accept: application/json' https://services.gradle.org/versions/current | jq .version | sed -e 's/"//g')-wrapper.jar.sha256)
       echo "  gradle-wrapper.jar" >> gradle-wrapper.jar.sha256
       sha256sum --check gradle-wrapper.jar.sha256
       rm gradle.zip
       cd ..
       cd ..
       echo Gradle Test
       ./gradlew test
       
  timestamp:
      runs-on: ubuntu-latest
      needs: testing
      steps:
      - uses: actions/checkout@v2
      - name: Timestamp Unit tests
        shell: bash
        run: |
           date >> ./timestamp  
           zone=$(TZ='Europe/Bratislava' LC_ALL=sk_SK.utf8 date -r ./timestamp)
           sed -i "7s/.*/- #####  Unit tests: $zone/" ./.github/README.md
           git config --global user.email ${{ secrets.EMAIL }}
           git config --global user.name ${{ secrets.NAME }}        
           git add ./.github/README.md
           git commit -m "timestamp" ./.github/README.md
           git push --force         
