name: Unit tests

on:
 pull_request_target:
 workflow_dispatch:
        
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Execute tests
      run: |
       echo -e "\033[31;1m Bundletool Version download Latest version\033[0m"
       Bundletool=$(curl -L -s -H 'Accept: application/json' https://github.com/google/bundletool/releases/latest)
       VersionBundletool=$(echo $Bundletool | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
       echo VersionBundletool = $VersionBundletool
       echo $VersionBundletool   
       URL=$(curl -s -L -o ./bundletool.jar https://github.com/google/bundletool/releases/download/$VersionBundletool/bundletool-all-$VersionBundletool.jar)     
       rm ./bundletool.jar
       echo --------------------------------------*
       cd ./gradle/wrapper
       rm gradle-wrapper.jar
       VersionGradle=$(curl -L -s -H 'Accept: application/json' https://services.gradle.org/versions/current | jq .version | sed -e 's/"//g')
       echo -e "\033[31;1m Gradle wrapper: \033[0m"
       echo VersionGradle = $VersionGradle
       echo $VersionGradle
       URL=$(curl -s -L -o gradle.zip https://services.gradle.org/distributions/gradle-$VersionGradle-src.zip)
       wrapper=$(unzip -j -d . gradle.zip gradle-$VersionGradle/gradle/wrapper/gradle-wrapper.jar)  
       SHA=$(curl -s --location --output gradle-wrapper.jar.sha256 https://services.gradle.org/distributions/gradle-$VersionGradle-wrapper.jar.sha256)
       echo "  gradle-wrapper.jar" >> gradle-wrapper.jar.sha256
       sha256sum --check gradle-wrapper.jar.sha256
       rm gradle-wrapper.jar.sha256
       rm gradle.zip
       cd ..
       cd ..
       timestamp=$(TZ='Europe/Bratislava' date)  
       sed -i 6i"distributionUrl=https\://services.gradle.org/distributions/gradle-$VersionGradle-all.zip" ./gradle/wrapper/gradle-wrapper.properties
       sed -i '7d' ./gradle/wrapper/gradle-wrapper.properties
       sed -i 7i"- #####  Unit tests: $timestamp" ./README.md
       sed -i '8d' ./README.md
       echo $timestamp
       git config pull.ff only
       git config --global user.email ${{ secrets.EMAIL }}
       git config --global user.name ${{ secrets.NAME }}
       git add -u
       git commit -m "$timestamp"
       git pull
       git push 
       
       
       
    - name: 🤖dependabot[bot]  Gradle update version
      if: ${{ github.actor == 'dependabot[bot]' }}
      run: |             
       chmod +x ./gradlew 
       echo -e "\033[31;1m Gradle Version switch to Latest version \033[0m"
       VersionGradle=$(curl -L -s -H 'Accept: application/json' https://services.gradle.org/versions/current | jq .version | sed -e 's/"//g')
       echo $VersionGradle
       ./gradlew wrapper --gradle-version=$VersionGradle --quiet
       ./gradlew -v 

       
       
    - name: 🤖dependabot[bot]  Gradle test
      if: ${{ github.actor == 'dependabot[bot]' }}
      run: | 
       echo -e "\033[31;1m Gradle Test \033[0m"
       ./gradlew test
      
      
    - name: 🤖dependabot[bot]  Gradle assembleDebug
      if: ${{ github.actor == 'dependabot[bot]' }}
      run: ./gradlew assembleDebug



     
