name: Lint
on:
 workflow_dispatch:
 

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew    
        shell: bash

      - name: lint
        run: ./gradlew lint

      - name: lintRelease
        run: ./gradlew lintRelease check


      - name: upload lint result
        uses: actions/upload-artifact@v2
        with:
         name: lint-results
         path: ./app/build/reports/*.*           


       




                  

         
 
      
 