name: Lint
on:
 workflow_dispatch:
 pull_request_target:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}
      CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        shell: bash

      - name: base64
        run: |
         echo $CERTIFICATE_BASE64 | base64 -i -d > ${{ github.workspace }}/app/android-LQ0F5.keystore

      - name: lint
        run: ./gradlew lint

      - name: lintRelease
        run: ./gradlew lintRelease


      - name: upload lint result
        uses: actions/upload-artifact@v4
        with:
         name: lint-results
         path: |
          ./app/build/reports/*.*
          ./build/reports/problems/*.*

