name: Build Relase
on:

 workflow_dispatch:
 schedule:
   - cron: '5 2 */86 * *'
jobs:
  build:
    name: BUILD SCRIPT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run scripts
      - shell: bash
        run: |
        echo "*** Make gradlew executable ***"
        chmod +x ./gradlew
         echo "*** assembleRelease ***"
        ./gradlew assembleRelease       
        echo "*** assembleDebug ***"
        ./gradlew assembleDebug
        echo "*** Download bundletool ***"
        curl -o /bundletool.jar https://github.com/google/bundletool/releases/download/1.7.0/bundletool-all-1.7.0.jar 
        echo "*** Build app bundle all (.aab) ***"
        ./gradlew app:bundle
        echo "*** Bundletool build apks all DEBUG (.apks) ***"
        java -jar ./bundletool.jar build-apks --bundle=./app/build/outputs/bundle/debug/app-debug.aab --output=./MyApp/app_debub_all.apks
        echo "*** Bundletool build apks all RELASE (.apks) ***"
        java -jar ./bundletool.jar build-apks --bundle=./app/build/outputs/bundle/relase/app-release.aab --output=./MyApp/app_relase_all.apks
        echo "*** Bundletool build apks all NOKIA 5 DEBUG (.apks) ***"
        java -jar ./bundletool.jar build-apks --device-spec=./nokia5.json --bundle=./app/build/outputs/bundle/debug/app-debug.aab --output=./MyApp/nokia5_debug.apks
        echo "*** Bundletool build apks all NOKIA 5 RELASE (.apks) ***"
        java -jar ./bundletool.jar build-apks --device-spec=./nokia5.json --bundle=./app/build/outputs/bundle/relase/app-release.aab --output=./MyApp/nokia5_relase.apks

  upload-artifact:
    name: UPLOAD ARTIFACTS
    - uses: actions/upload-artifact@v2
      with:
       name: debug&relase_APK
       path: |
        ./app/build/outputs/apk/debug/*.apk
        ./app/build/outputs/apk/relase/*.apk
       name: debug&relase_APKS
       path: |
        ./MyApp/app_debub_all.apks
        ./MyApp/app_relase_all.apks
       name: debug&relase_Nokia5_APKS
       path: |
        ./MyApp/nokia5_debug.apks
        ./MyApp/nokia5_relase.apks
       name: debug&relase_AAB
       path: |
        ./app/build/outputs/bundle/debug/*.aab
        ./app/build/outputs/bundle/relase/*.aab

