name: Build Relase
on:

 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}} 
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: echo "*** Make gradlew executable ***"
        run: chmod +x ./gradlew
      - name: echo "*** Download bundletool ***"
        run: |
          RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/google/bundletool/releases/latest)
          VERSION=$(echo $RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
          echo VERSION = $VERSION
          URL=$(curl -L -o ./bundletool.jar https://github.com/google/bundletool/releases/download/$(echo $RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')/bundletool-all-$(echo $RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/').jar)
      - name: Build nokia5.json file
        run: |
         JSON_N5='{"supportedAbis":["arm64-v8a"],"supportedLocales":["sk"],"screenDensity":282,"sdkVersion":28}\n'
         printf "$JSON_N5" "$supportedAbis" "$supportedLocales" "$screenDensity" "$sdkVersion" >> ./nokia5.json
      - name:  echo "*** assembleRelease ***"
        run: ./gradlew assembleRelease      
      - name: echo "*** assembleDebug ***"
        run: ./gradlew assembleDebug    
      - name: echo "*** Build app bundle all (.aab) ***"
        run: ./gradlew app:bundle      
      - name: echo "*** Bundletool build apks all DEBUG (.apks) ***"
        run: java -jar ./bundletool.jar build-apks --bundle=./app/build/outputs/bundle/debug/app-debug.aab --output=./MyApp/data_live_wallpaper_debug_all.apks --ks=./app/android-LQ0F5.keystore --ks-pass=pass:${{ secrets.KEYSTORE_PASSWORD }} --key-pass=pass:${{ secrets.KEY_PASSWORD }} --ks-key-alias=${{ secrets.KEY_ALIAS }}
      - name: echo "*** Bundletool build apks all RELASE (.apks) ***"
        run: java -jar ./bundletool.jar build-apks --bundle=./app/build/outputs/bundle/release/app-release.aab --output=./MyApp/data_live_wallpaper_relase_all.apks --ks=./app/android-LQ0F5.keystore --ks-pass=pass:${{ secrets.KEYSTORE_PASSWORD }} --key-pass=pass:${{ secrets.KEY_PASSWORD }} --ks-key-alias=${{ secrets.KEY_ALIAS }}
      - name: echo "*** Bundletool build apks all NOKIA 5 DEBUG (.apks) ***"
        run: java -jar ./bundletool.jar build-apks --device-spec=./nokia5.json --bundle=./app/build/outputs/bundle/debug/app-debug.aab --output=./MyApp/data_live_wallpaper_nokia5_debug.apks --ks=./app/android-LQ0F5.keystore --ks-pass=pass:${{ secrets.KEYSTORE_PASSWORD }} --key-pass=pass:${{ secrets.KEY_PASSWORD }} --ks-key-alias=${{ secrets.KEY_ALIAS }}
      - name: echo "*** Bundletool build apks all NOKIA 5 RELASE (.apks) ***"
        run: java -jar ./bundletool.jar build-apks --device-spec=./nokia5.json --bundle=./app/build/outputs/bundle/release/app-release.aab --output=./MyApp/data_live_wallpaper_nokia5_relase.apks --ks=./app/android-LQ0F5.keystore --ks-pass=pass:${{ secrets.KEYSTORE_PASSWORD }} --key-pass=pass:${{ secrets.KEY_PASSWORD }} --ks-key-alias=${{ secrets.KEY_ALIAS }}

      - name: debug&relase_APK
        uses: actions/upload-artifact@v2
        with:
         name: debug&relase_APK
         path: |
          ./app/build/outputs/apk/debug/data_live_wallpaper_debug.apk
          ./app/build/outputs/apk/release/data_live_wallpaper_release.apk
      - name: debug&relase_APKS
        uses: actions/upload-artifact@v2
        with:
         name: debug&relase_APKS
         path: |
          ./MyApp/data_live_wallpaper_debug_all.apks
          ./MyApp/data_live_wallpaper_relase_all.apks
      - name: debug&relase_Nokia5_APKS
        uses: actions/upload-artifact@v2
        with:
         name: debug&relase_Nokia5_APKS
         path: |
          ./MyApp/data_live_wallpaper_nokia5_debug.apks
          ./MyApp/data_live_wallpaper_nokia5_relase.apks
      -  name: debug&relase_AAB
         uses: actions/upload-artifact@v2
         with:
          name: debug&relase_AAB
          path: |
           ./app/build/outputs/bundle/debug/app-debug.aab
           ./app/build/outputs/bundle/release/app-release.aab

      - uses: actions/download-artifact@v2
        with:
         path: ./artifacts/
         
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
         repo_token: "${{ secrets.GITHUB_TOKEN }}"
         prerelease: false
         title: data_live_wallpaper_artifacts
         automatic_release_tag: all_artifacts
         files: |           
            ./artifacts/debug&relase_AAB/debug/app-debug.aab
            ./artifacts/debug&relase_AAB/release/app-release.aab
            ./artifacts/debug&relase_APK/debug/data_live_wallpaper_debug.apk
            ./artifacts/debug&relase_APK/release/data_live_wallpaper_release.apk
            ./artifacts/debug&relase_APKS/data_live_wallpaper_debug_all.apks
            ./artifacts/debug&relase_APKS/data_live_wallpaper_relase_all.apks
            ./artifacts/debug&relase_Nokia5_APKS/data_live_wallpaper_nokia5_debug.apks
            ./artifacts/debug&relase_Nokia5_APKS/data_live_wallpaper_nokia5_relase.apks


      - name: echo "*** ReadmE ***"
        run: |
          rm -f ./.github/README.md
          find ./artifacts/ -type f -print0 | xargs -0 sha256sum >> ./sha256.md
          sed 's/  /|/1g' ./sha256.md  >> ./README1.md
          sed -i 1i"## SHA-256" ./README1.md
          sed -i 2i"**sha256** | **file**" ./README1.md
          sed -i 3i"---: | :---:" ./README1.md
          cat ./README.md ./README1.md >> ./.github/README.md
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}        
          git add ./.github/README.md
          git commit -m "README" ./.github/README.md 
          git push --force 
