name: Build Relase
on:

 workflow_dispatch:
 schedule:
   - cron: '5 2 */86 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: echo "*** Make gradlew executable ***"
        run: chmod +x ./gradlew            
      - name:  echo "*** assembleRelease ***"
        run: ./gradlew assembleRelease       
      - name: echo "*** assembleDebug ***"
        run: ./gradlew assembleDebug
      - name: echo "*** Build app bundle all (.aab) ***"
        run: ./gradlew app:bundle
      - name: echo "*** Bundletool build apks all DEBUG (.apks) ***"
        run: java -jar ./bundletool.jar build-apks --bundle=./app/build/outputs/bundle/debug/app-debug.aab --output=./MyApp/data_live_wallpaper_debug_all.apks
      - name: echo "*** Bundletool build apks all RELASE (.apks) ***"
        run: java -jar ./bundletool.jar build-apks --bundle=./app/build/outputs/bundle/release/app-release.aab --output=./MyApp/data_live_wallpaper_relase_all.apks
      - name: echo "*** Bundletool build apks all NOKIA 5 DEBUG (.apks) ***"
        run: java -jar ./bundletool.jar build-apks --device-spec=./nokia5.json --bundle=./app/build/outputs/bundle/debug/app-debug.aab --output=./MyApp/data_live_wallpaper_nokia5_debug.apks
      - name: echo "*** Bundletool build apks all NOKIA 5 RELASE (.apks) ***"
        run: java -jar ./bundletool.jar build-apks --device-spec=./nokia5.json --bundle=./app/build/outputs/bundle/release/app-release.aab --output=./MyApp/data_live_wallpaper_nokia5_relase.apks

      - name: debug&relase_APK
        uses: actions/upload-artifact@v2
        with:
         name: debug&relase_APK
         path: |
          ./app/build/outputs/apk/debug/data_live_wallpaper_debug.apk
          ./app/build/outputs/apk/release/data_live_wallpaper_release.apk
      - name: debug&relase_APKS
        uses: actions/upload-artifact@v2
        with:
         name: debug&relase_APKS
         path: |
          ./MyApp/data_live_wallpaper_debug_all.apks
          ./MyApp/data_live_wallpaper_relase_all.apks
      - name: debug&relase_Nokia5_APKS
        uses: actions/upload-artifact@v2
        with:
         name: debug&relase_Nokia5_APKS
         path: |
          ./MyApp/data_live_wallpaper_nokia5_debug.apks
          ./MyApp/data_live_wallpaper_nokia5_relase.apks
      -  name: debug&relase_AAB
         uses: actions/upload-artifact@v2
         with:
          name: debug&relase_AAB
          path: |
           ./app/build/outputs/bundle/debug/app-debug.aab
           ./app/build/outputs/bundle/release/app-release.aab

      - uses: actions/download-artifact@v2
        with:
         path: ./artifacts/
         
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
         repo_token: "${{ secrets.GITHUB_TOKEN }}"
         prerelease: false
         title: data_live_wallpaper_artifacts
         automatic_release_tag: apk, apks, aab
         files: |           
            ./artifacts/debug&relase_AAB/debug/app-debug.aab
            ./artifacts/debug&relase_AAB/release/app-release.aab
            ./artifacts/debug&relase_APK/debug/data_live_wallpaper_debug.apk
            ./artifacts/debug&relase_APK/release/data_live_wallpaper_release.apk
            ./artifacts/debug&relase_APKS/data_live_wallpaper_debug_all.apks
            ./artifacts/debug&relase_APKS/data_live_wallpaper_relase_all.apks
            ./artifacts/debug&relase_Nokia5_APKS/data_live_wallpaper_nokia5_debug.apks
            ./artifacts/debug&relase_Nokia5_APKS/data_live_wallpaper_nokia5_relase.apks
