name: transparency
run-name: ${{ github.workflow }} ✅ ${{ github.actor }} ✅ ${{ github.event_name}}
on:
 workflow_dispatch:

jobs:
  key:
    runs-on: ubuntu-latest
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}
      GH_TOKEN: ${{ github.TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: keytool --help
        run: keytool --help


      - name: keytool
        run: |
          keytool -export \
          -alias ${{ secrets.KEY_ALIAS }} \
          -keystore ./app/android-LQ0F5.keystore \
          -rfc \
          -file ./transparency.cert
        shell: bash


      - name: base64
        run: |
         base64 -i ./transparency.cert > cert.base64
         gh secret set CERTIFICATE_BASE64 < cert.base64


      - name: tree
        env:
          CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
        run: tree -h -L 2 ./