name: transparency
run-name: ${{ github.workflow }} ✅ ${{ github.actor }} ✅ ${{ github.event_name}}
on:
 workflow_dispatch:

jobs:
  key:
    runs-on: ubuntu-latest
    permissions: write-all

    env:
      KEYSTORE_PASSWORD:
      KEY_ALIAS:
      KEY_PASSWORD:
      GH_TOKEN: ${{ github.TOKEN }}

    steps:
      - uses: actions/checkout@v3


      - name: tree
        run: gh secret set SECREE